spring:
  application:
    name: financetracker

  datasource:
    url: jdbc:postgresql://localhost:5432/financetracker
    username: postgres
    password: MyP@ssword!123
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

